name: flutter_autolink_text
description: Flutter Autolink Text Widget.
version: 1.0.0+2
author: "Pavel Gershevich <fognaturedevelop@gmail.com>"
homepage: https://github.com/FogNature/flutter_autolink_text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
